"""Job lifecycle events emitted by core pipeline workers."""

from enum import StrEnum


class JobEvent(StrEnum):
    JOB_STARTED = "JOB_STARTED"
    VALIDATING_INPUT = "VALIDATING_INPUT"
    CHECKING_FFMPEG_CAPABILITIES = "CHECKING_FFMPEG_CAPABILITIES"
    FETCHING_PLAYLIST = "FETCHING_PLAYLIST"
    ANALYZING_PLAYLIST = "ANALYZING_PLAYLIST"
    MEDIA_PLAYLIST_INPUT_DETECTED = "MEDIA_PLAYLIST_INPUT_DETECTED"
    SUBTITLE_FOUND = "SUBTITLE_FOUND"
    SUBTITLE_NOT_FOUND = "SUBTITLE_NOT_FOUND"
    SELECTING_SUBTITLE_TRACK = "SELECTING_SUBTITLE_TRACK"
    FETCHING_SUBTITLE_PLAYLIST = "FETCHING_SUBTITLE_PLAYLIST"
    DOWNLOADING_SUBTITLE = "DOWNLOADING_SUBTITLE"
    EXTRACTING_SUBTITLE_WITH_FFMPEG = "EXTRACTING_SUBTITLE_WITH_FFMPEG"
    MERGING_SUBTITLE_SEGMENTS = "MERGING_SUBTITLE_SEGMENTS"
    NORMALIZING_SUBTITLE_TIMESTAMPS = "NORMALIZING_SUBTITLE_TIMESTAMPS"
    VALIDATING_SUBTITLE_OUTPUT = "VALIDATING_SUBTITLE_OUTPUT"
    FALLING_BACK_TO_STT = "FALLING_BACK_TO_STT"
    CHECKING_HLS_ENCRYPTION = "CHECKING_HLS_ENCRYPTION"
    EXTRACTING_AUDIO = "EXTRACTING_AUDIO"
    SPLITTING_AUDIO = "SPLITTING_AUDIO"
    TRANSCRIBING = "TRANSCRIBING"
    POSTPROCESSING = "POSTPROCESSING"
    EXPORTING = "EXPORTING"
    REDACTING_LOGS = "REDACTING_LOGS"
    CANCELLING = "CANCELLING"
    JOB_DONE = "JOB_DONE"
    JOB_ERROR = "JOB_ERROR"
    JOB_CANCELLED = "JOB_CANCELLED"

